### ISSUE TITLE
Стили не собираются?

### ISSUE THREAD

**Issue by popoff** [yoksel/project-scaffold#1]
Спасибо за полезный шаблон: ничего лишнего, но в то же время всего хватает. Клонировал, чтобы потестить для своего проектика. HTML и JS собираются без проблем, но что-то не так со сборкой стилей. Любые изменения в scss-файлах в папке "src" при сборке игрнорируются. При этом в терминале никаких ошибок не выводится.

**Comment by yoksel** [comment]
Прошу прощения за задержку с ответом.

Потестила, всё собирается, изменения в стилях отслеживаются. Если проблема ещё не разрешилась, попробуйте проверить, что нужный вам файл импортирован в styles.scss

**Comment by popoff** [comment]
Спасибо, действительно пропустил импорт, собирается нормально
